
<div class="signin-form">
    <div class="signin-logo">
        <img src="/assets/src/logo/logo.png" alt="<?php echo SITE_NAME; ?>">
    </div>
    <h1 class="signin-title">URL送信完了</h1>
    <p class="signin-description">ご入力いただいたメールアドレスにパスワード再設定用のURLをお送りしました。</p>
    <p class="signin-description">メールからURLをクリックし、パスワードを再設定してください。</p>

    <p class="signin-pagelink"><a href="/login/">ログインページへ</a></p>
</div>
