
<div class="signin-form">
    <div class="signin-logo">
        <img src="/assets/src/logo/logo.png" alt="<?php echo SITE_NAME; ?>">
    </div>
    <h1 class="signin-title">ユーザー退会完了</h1>
    <p class="signin-description"><?php echo SITE_NAME; ?>の退会手続きが終了いたしました。</p>
    <p class="signin-description">この度は<?php echo SITE_NAME; ?>をご利用頂いただきまして、誠にありがとうございました。</p>

    <p class="signin-pagelink"><a href="/">トップページへ</a></p>
</div>
